name: CMake Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          # clang build on Debug & Release
          - name: Debug clang
            build_type: Debug
            cc: clang
            cxx: clang++
            parralel: --parallel
          - name: Release clang
            build_type: Release
            cc: clang
            cxx: clang++
            parralel: --parallel
          # gcc build on Debug & Release - no parallel builds due to RAM usage
          - name: Debug GCC
            build_type: Debug
            cc: gcc
            cxx: g++
            parralel: ~
          - name: Release GCC
            build_type: Release
            cc: gcc
            cxx: g++
            parralel: ~
    steps:
    - uses: actions/checkout@v3

    - name: Configure VM
      run: sh ${{github.workspace}}/tools/linux/scripts/trusty-install-deps.sh

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.cxx}} -DCMAKE_C_COMPILER=${{matrix.cc}} -DCINDER_BUILD_TESTS=1

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}} ${{matrix.parallel}}

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ${{github.workspace}}/build/${{matrix.build_type}}/UnitTests/UnitTests
