name: VC2022

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        config: [Debug, Release]
    
    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: MSBuild Setup
        uses: microsoft/setup-msbuild@v1.1
        with:
          msbuild-architecture: 'x64'

      - name: Build
        working-directory: ${{github.workspace}}
        run: msbuild proj\vc2022\cinder.sln /m /t:rebuild /p:Configuration=${{matrix.config}}

      - name: Build Unit Tests
        working-directory: ${{github.workspace}}\test\unit
        run: msbuild vc2022\unit.sln /m /t:rebuild /p:Configuration=${{matrix.config}}

      - name: Run Unit Tests
        working-directory: ${{github.workspace}}\test\unit
        run: vc2022\build\v143\${{matrix.config}}\x64\CinderUnitTests.exe
